In [1]:
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Kelulusan Test.xls')
df.head(5)

NAMA JENIS KELAMIN STATUS MAHASISWA  UMUR   STATUS NIKAH  \
0                  UNAMA   LAKI - LAKI        MAHASISWA    24  BELUM MENIKAH   
1  LEYLA TRIYANA PRATIWI     PEREMPUAN        MAHASISWA    26  BELUM MENIKAH   
2  VERIS SOFIYAN PRAYOGA   LAKI - LAKI        MAHASISWA    29  BELUM MENIKAH   
3   ADITYA AKBAR NUGRAHA   LAKI - LAKI        MAHASISWA    27  BELUM MENIKAH   
4       ERNA EKA RIYANTI     PEREMPUAN        MAHASISWA    25  BELUM MENIKAH   

   IPS 1  IPS 2  IPS 3  IPS 4  IPS 5  IPS 6  IPS 7  IPS 8  IPK   \
0   3.17   2.70   3.23   2.41   3.00   2.47   1.75   0.00  2.75   
1   3.60   3.50   3.42   2.85   3.31   2.95   2.18   0.00  3.39   
2   2.67   2.66   2.93   3.14   2.92   2.64   2.88   0.50  2.81   
3   2.48   2.86   2.09   2.55   2.55   2.43   2.55   2.17  2.82   
4   3.19   3.08   3.31   2.83   3.36   2.73   3.06   0.00  3.09   

  STATUS KELULUSAN  
0            TEPAT  
1            TEPAT  
2            TEPAT  
3            TEPAT  
4            TEPAT

In [3]:
data = df[['IPS 1', 'IPS 2', 'IPS 3', 'IPS 4', 'IPS 5']]
data

IPS 1  IPS 2  IPS 3  IPS 4  IPS 5
0     3.17   2.70   3.23   2.41   3.00
1     3.60   3.50   3.42   2.85   3.31
2     2.67   2.66   2.93   3.14   2.92
3     2.48   2.86   2.09   2.55   2.55
4     3.19   3.08   3.31   2.83   3.36
..     ...    ...    ...    ...    ...
140   1.98   2.50   2.14   2.77   2.61
141   2.74   2.75   2.55   3.00   2.98
142   2.74   2.75   2.55   3.00   2.98
143   3.02   2.94   3.25   2.87   3.00
144   3.10   3.06   3.00   3.23   2.79

[145 rows x 5 columns]

In [4]:
data_train = data.head(5)
data_train

IPS 1  IPS 2  IPS 3  IPS 4  IPS 5
0   3.17   2.70   3.23   2.41   3.00
1   3.60   3.50   3.42   2.85   3.31
2   2.67   2.66   2.93   3.14   2.92
3   2.48   2.86   2.09   2.55   2.55
4   3.19   3.08   3.31   2.83   3.36

In [5]:
data_test = data.tail(1)
data_test

IPS 1  IPS 2  IPS 3  IPS 4  IPS 5
144    3.1   3.06    3.0   3.23   2.79

In [6]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 144 to 144
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   IPS 1   1 non-null      float64
 1   IPS 2   1 non-null      float64
 2   IPS 3   1 non-null      float64
 3   IPS 4   1 non-null      float64
 4   IPS 5   1 non-null      float64
dtypes: float64(5)
memory usage: 172.0 bytes


In [7]:
trainn = data_train.to_numpy()
testt = data_test.to_numpy()

### Jaccard Similarity

In [8]:
import numpy as np
from scipy.spatial.distance import jaccard
from sklearn.metrics import jaccard_score


In [9]:

# Menghitung Jaccard Similarity
jaccard_similarity = []
for i in range(len(trainn)):
    intersection = np.intersect1d(trainn[i], testt)
    union = np.union1d(trainn[i], testt)
    similarity = len(intersection) / len(union)
    jaccard_similarity.append(similarity)

# Menampilkan hasil Jaccard Similarity untuk setiap data train
for i, similarity in enumerate(jaccard_similarity):
    print(f"Jaccard Similarity antara data test dan data train ke-{i+1}: {similarity}")

Jaccard Similarity antara data test dan data train ke-1: 0.25
Jaccard Similarity antara data test dan data train ke-2: 0.0
Jaccard Similarity antara data test dan data train ke-3: 0.0
Jaccard Similarity antara data test dan data train ke-4: 0.0
Jaccard Similarity antara data test dan data train ke-5: 0.0


In [10]:
# Menghitung Jaccard Similarity
def jaccard_similarity(set1, set2):
    intersection = len(set(set1).intersection(set2))
    union = len(set(set1).union(set2))
    return intersection / union

similarities = []

for train_data in data_train:
    similarity = jaccard_similarity(data_train, data_test)
    similarities.append(similarity)

print("Jaccard Similarities:")
for i, similarity in enumerate(similarities):
    print(f"Data Train ke- {i + 1}: {similarity:.2f}")

Jaccard Similarities:
Data Train ke- 1: 1.00
Data Train ke- 2: 1.00
Data Train ke- 3: 1.00
Data Train ke- 4: 1.00
Data Train ke- 5: 1.00


### Mahalanobis Distance

In [11]:
trainn

array([[3.17, 2.7 , 3.23, 2.41, 3.  ],
       [3.6 , 3.5 , 3.42, 2.85, 3.31],
       [2.67, 2.66, 2.93, 3.14, 2.92],
       [2.48, 2.86, 2.09, 2.55, 2.55],
       [3.19, 3.08, 3.31, 2.83, 3.36]])

In [12]:
testt

array([[3.1 , 3.06, 3.  , 3.23, 2.79]])

In [13]:
import numpy as np

# Data train
data_train = np.array([
    [3.24, 3.06, 2.79, 2.73, 3.02],
    [2.83, 3.02, 3.02, 3.63, 3.21],
    [2.83, 3.00, 2.54, 3.36, 2.79],
    [3.00, 3.08, 3.02, 3.07, 2.88],
    [3.52, 3.52, 3.31, 3.33, 3.30],
    [2.29, 0.50, 0.16, 0.32, 1.13]
])

# Data test
data_test = np.array([3.1, 3.06, 3.0, 3.23, 2.79])

# Calculate the covariance matrix of the training data
cov_matrix = np.cov(data_train.T)

# Calculate the inverse of the covariance matrix
inv_cov_matrix = np.linalg.inv(cov_matrix)

# Calculate Mahalanobis Distance manually
distances = []
for i in range(len(data_train)):
    diff = data_train[i] - data_test
    dist = np.sqrt(np.dot(np.dot(diff, inv_cov_matrix), diff))
    distances.append(dist)

# Print the Mahalanobis Distances
print("Mahalanobis Distances between data_train and data_test:")
for i, dist in enumerate(distances):
    print(f"Data train ke-{i+1}: {dist}")


Mahalanobis Distances between data_train and data_test:
Data train ke-1: 5.797577351038265
Data train ke-2: 4.700016611794527
Data train ke-3: 4.546397530122099
Data train ke-4: 3.5453285303808646
Data train ke-5: 3.3914229765059236
Data train ke-6: 4.452377588802786


In [14]:
from scipy.spatial import distance
# Menghitung Mahalanobis Distance
distances = []
for i in range(len(trainn)):
    dist = distance.mahalanobis(trainn[0], trainn[i], np.linalg.inv(np.cov(trainn.T)))
    distances.append(dist)

# Menampilkan hasil
print("Mahalanobis Distance antara data train dan data test:")
for i, dist in enumerate(distances):
    print(f"Data train ke-{i+1}: {dist}")


Mahalanobis Distance antara data train dan data test:
Data train ke-1: 0.0
Data train ke-2: 2.5670995305986875
Data train ke-3: 3.2444182837605884
Data train ke-4: 2.3515952032609695
Data train ke-5: 2.731300056749532


### Chebyshev distance

In [15]:
from sklearn.metrics import pairwise_distances
# Menghitung jarak Chebyshev antara data train dan data test
distances = pairwise_distances(trainn, testt, metric='chebyshev')

# Menampilkan hasil
print("Jarak Chebyshev antara data train dan data test:")
for i, distance in enumerate(distances):
    print(f"Data train ke-{i+1}: {distance[0]}")

Jarak Chebyshev antara data train dan data test:
Data train ke-1: 0.8199999999999998
Data train ke-2: 0.52
Data train ke-3: 0.43000000000000016
Data train ke-4: 0.9100000000000001
Data train ke-5: 0.5699999999999998


### Minkowski distance

In [16]:
# Menghitung jarak Minkowski dengan p=3 (Contoh)
distances = pairwise_distances(trainn, testt, metric='minkowski', p=3)

# Menampilkan hasil
print("Jarak Minkowski antara data train dan data test:")
for i, distance in enumerate(distances):
    print(f"Data train ke-{i+1}: {distance[0]}")

Jarak Minkowski antara data train dan data test:
Data train ke-1: 0.8526079073826127
Data train ke-2: 0.7828386595627493
Data train ke-3: 0.5274950023110883
Data train ke-4: 1.0992156943624947
Data train ke-5: 0.6539958975636322


### Euclidean distance

In [17]:
# Menghitung jarak Euclidean
distances = pairwise_distances(trainn, testt, metric='euclidean')

# Menampilkan hasil
print("Jarak Euclidean antara data train dan data test:")
for i, distance in enumerate(distances):
    print(f"Data train ke-{i+1}: {distance[0]}")

Jarak Euclidean antara data train dan data test:
Data train ke-1: 0.9507365565707464
Data train ke-2: 1.0172511980823566
Data train ke-3: 0.6122091146005648
Data train ke-4: 1.3313526955694377
Data train ke-5: 0.7677890335241797


### Manhattan distance

In [18]:
# Menghitung jarak Manhattan
distances = pairwise_distances(trainn, testt, metric='manhattan')

# Menampilkan hasil
print("Jarak Manhattan antara data train dan data test:")
for i, distance in enumerate(distances):
    print(f"Data train ke-{i+1}: {distance[0]}")

Jarak Manhattan antara data train dan data test:
Data train ke-1: 1.6899999999999995
Data train ke-2: 2.26
Data train ke-3: 1.1199999999999997
Data train ke-4: 2.650000000000001
Data train ke-5: 1.3899999999999997


### Cosine Similarity

In [19]:
trainn

array([[3.17, 2.7 , 3.23, 2.41, 3.  ],
       [3.6 , 3.5 , 3.42, 2.85, 3.31],
       [2.67, 2.66, 2.93, 3.14, 2.92],
       [2.48, 2.86, 2.09, 2.55, 2.55],
       [3.19, 3.08, 3.31, 2.83, 3.36]])

In [20]:
from sklearn.metrics.pairwise import cosine_similarity
# Menghitung cosine similarity
similarity_scores = cosine_similarity(testt, trainn)

# Menampilkan hasil similarity
print("Cosine Similarity antara data test dan data train:")
for i, score in enumerate(similarity_scores[0]):
    print(f"Data train ke-{i+1}: {score}")

Cosine Similarity antara data test dan data train:
Data train ke-1: 0.9906373670681219
Data train ke-2: 0.9944518172734924
Data train ke-3: 0.9973546362949611
Data train ke-4: 0.9945988740995836
Data train ke-5: 0.994614208542635
